"use client";

import "./globals.css";
import { Container, CssBaseline, ThemeProvider } from "@mui/material";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import theme from "@todolist/styles/theme";
import { ToastContainer } from "react-toastify";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();
  return (
    <html lang="en">
      <body>
        <QueryClientProvider client={queryClient}>
          <ToastContainer />
          <ThemeProvider theme={theme}>
          <CssBaseline />
          <Container sx={{ height: "100vh" }}>{children}</Container>
          </ThemeProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
